ALTER TABLE users
    ADD COLUMN IF NOT EXISTS timezone TEXT NOT NULL DEFAULT 'UTC';

ALTER TABLE habits
    ADD COLUMN IF NOT EXISTS is_paused    BOOLEAN     NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS goal_days    INT         NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS best_streak  INT         NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS snooze_until TIMESTAMPTZ;
